# Generated by Django 4.2 on 2023-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_staff_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='services',
            field=models.ManyToManyField(to='appointments.service'),
        ),
    ]
